from fastapi import APIRouter, HTTPException
from controllers import UserController

router = APIRouter()

@router.post("/users/")
async def create_user(user):
    return await UserController.create_user(user)

@router.get("/users/{user_id}")
async def get_user(user_id):
    try:
        return await UserController.get_user(user_id)
    except Exception:
        raise HTTPException(status_code=404, detail="User not found")